version: "3.8"
services:
  postgres-db:
    container_name: chat-postgres
    image: postgres # use latest official postgres version
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - "5432:5432" # outside port, inside port

    volumes:
      - ./postgresql_data:/var/lib/postgresql/data

volumes:
  postgresql_data:
    driver: local